### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [gcraill/prj-rev-bwfs-dasmoto#5]
Grade: Exceeds expectations

Summary: Very nice job on this project. The code is very organized and well thought out. You are handling css very well with extracting reusable styling into classes. The trend in class naming has slightly shifted from style description to more modular naming. This article touches on this as well as some other good practices: http://learn.shayhowe.com/html-css/writing-your-best-code/
There are many different naming conventions out there, here is a link to BEM which also links to other style, I would recommend checking them out. http://getbem.com/introduction/

**Comment by gcraill** [comment]
Cheers, bookmarked and added to reading list.
